import { describe, expect, it } from "vitest";
// option C:清洗归后端。golden 用例现测后端权威 cleaner(移植前在 web/src/lib,已删)。
import { cleanClaudeUserMessage as cleanUserMessage } from "../src/claudeCodeHistory/myMessages.js";

describe("cleanUserMessage", () => {
  it("保留纯手打文本", () => {
    expect(cleanUserMessage("帮我看下这个 bug")).toBe("帮我看下这个 bug");
  });

  it("命令调用 → 紧凑 /名字(空参数)", () => {
    const raw =
      "<command-message>graphify is running</command-message>\n" +
      "<command-name>/graphify</command-name>\n" +
      "<command-args></command-args>";
    expect(cleanUserMessage(raw)).toBe("/graphify");
  });

  it("剥掉 local-command-stdout", () => {
    expect(
      cleanUserMessage("<local-command-stdout>some output</local-command-stdout>")
    ).toBe("");
  });

  it("剥掉 system-reminder 块、保留周围手打文本", () => {
    const raw =
      "真正的问题\n<system-reminder>这是注入的提醒,内容很长\n跨多行</system-reminder>";
    expect(cleanUserMessage(raw)).toBe("真正的问题");
  });

  it("剥掉 Caveat 声明、保留正文", () => {
    const raw =
      "Caveat: The messages below were generated by the user while running local commands. " +
      "DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.\n\n实际内容";
    expect(cleanUserMessage(raw)).toBe("实际内容");
  });

  it("剥掉 [Request interrupted by user] 两种形态", () => {
    expect(cleanUserMessage("[Request interrupted by user]")).toBe("");
    expect(
      cleanUserMessage("[Request interrupted by user for tool use]后面继续问")
    ).toBe("后面继续问");
  });

  it("剥完只剩空白 → 空串", () => {
    expect(cleanUserMessage("   \n  ")).toBe("");
  });

  it("混合脏轮(非命令):剥注入、留手打那段", () => {
    const raw = "继续帮我实现这个功能\n<system-reminder>injected</system-reminder>";
    expect(cleanUserMessage(raw)).toBe("继续帮我实现这个功能");
  });

  it("命令调用(含 command-name)→ /名字", () => {
    const raw =
      "<command-message>gstack-plan-eng-review</command-message>\n" +
      "<command-name>/gstack-plan-eng-review</command-name>";
    expect(cleanUserMessage(raw)).toBe("/gstack-plan-eng-review");
  });

  it("命令调用带参数 → /名字 参数", () => {
    const raw =
      "<command-name>/karpathy-llm-wiki</command-name>\n" +
      "<command-args>Ingest the page</command-args>";
    expect(cleanUserMessage(raw)).toBe("/karpathy-llm-wiki Ingest the page");
  });

  it("裸 skill 正文轮(Base directory 前缀,无命令标签)整轮丢弃", () => {
    const raw =
      "Base directory for this skill: /Users/x/.claude/skills/foo\n\n" +
      "<!-- AUTO-GENERATED from SKILL.md.tmpl -->\n\n## Preamble\n```bash\necho hi\n```";
    expect(cleanUserMessage(raw)).toBe("");
  });

  it("空输入安全", () => {
    expect(cleanUserMessage("")).toBe("");
  });

  // v4(2026-08-17):bash-* 三个标签。实测语料里 input 与 stdout/stderr 是两条独立
  // user 消息(各 63 条),性质相反,所以剥法必须分开 —— 一刀切会让 63 条你敲过的命令消失。
  describe("bash-* 控制标签(v4)", () => {
    it("bash-input 只剥标签、留下你敲的命令", () => {
      expect(cleanUserMessage("<bash-input>ls</bash-input>")).toBe("ls");
      expect(cleanUserMessage("<bash-input>git status</bash-input>")).toBe(
        "git status"
      );
    });

    it("bash-stdout / bash-stderr 整块剥(机器输出)", () => {
      expect(
        cleanUserMessage("<bash-stdout>client.go\ncmd\ngo.mod</bash-stdout>")
      ).toBe("");
      expect(cleanUserMessage("<bash-stderr>fatal: not a repo</bash-stderr>")).toBe(
        ""
      );
    });

    it("真实形态:stdout 与空 stderr 连在一起 → 整条变空", () => {
      const raw =
        "<bash-stdout>On branch main\nnothing to commit</bash-stdout>" +
        "<bash-stderr></bash-stderr>";
      expect(cleanUserMessage(raw)).toBe("");
    });

    it("标签字面不会残留进 cleaned_text(否则会当人类词汇进 FTS)", () => {
      const cleaned = cleanUserMessage("<bash-input>echo hi</bash-input>");
      expect(cleaned).not.toContain("bash-input");
      expect(cleaned).not.toContain("<");
    });
  });
});
