import { describe, expect, it } from "vitest";
import { parseUserMessage } from "../web/src/util/parseUserMessage.js";
import { sgrParse } from "../web/src/util/sgrParse.js";

/**
 * Golden fixtures —— 形态取自真实 Claude Code jsonl 里的 user 消息(codex #10:
 * 合成单测不够,锁真实标签形态 + SGR 残骸)。ai2nao 是公开仓 + gitleaks 拦真实家
 * 目录,故任何路径都占位成 /tmp/...。
 */

// 1) /model 命令回显:stdout 里带无-ESC 的 [1m..[22m 加粗残骸(实测形态)。
const MODEL_ECHO =
  "<local-command-stdout>Set model to [1mOpus 4.7 (1M context) (default)[22m " +
  "and saved as your default for new sessions with [1mmax[22m effort</local-command-stdout>";

// 2) 斜杠命令 /graphify:message + name + args 三件套。
const GRAPHIFY_CMD =
  "<command-message>graphify</command-message>\n" +
  "            <command-name>/graphify</command-name>\n" +
  "            <command-args>.</command-args>";

// 3) caveat + 真人正文混合(截图里那种)。
const CAVEAT_PLUS_TEXT =
  "<local-command-caveat>Caveat: The messages below were generated by the " +
  "user while running local commands. DO NOT respond to these messages.</local-command-caveat>\n" +
  "帮我把 /tmp/repo 这个目录索引一下";

describe("parseUserMessage golden —— 真实 jsonl 形态", () => {
  it("1) /model stdout:切一个 stdout 段,SGR 残骸能还原成加粗", () => {
    const segs = parseUserMessage(MODEL_ECHO);
    expect(segs).toHaveLength(1);
    expect(segs[0].kind).toBe("stdout");
    const raw = (segs[0] as { kind: "stdout"; raw: string }).raw;
    const spans = sgrParse(raw);
    // 有加粗 span,且加粗的正是 Opus 4.7 与 max。
    const bold = spans.filter((s) => s.bold).map((s) => s.text);
    expect(bold).toEqual(["Opus 4.7 (1M context) (default)", "max"]);
    // 拼回去无残骸(方括号码被吃掉)。
    expect(spans.map((s) => s.text).join("")).toBe(
      "Set model to Opus 4.7 (1M context) (default) and saved as your default for new sessions with max effort"
    );
  });

  it("2) /graphify:三字段聚成一个 command 段", () => {
    expect(parseUserMessage(GRAPHIFY_CMD)).toEqual([
      { kind: "command", message: "graphify", name: "/graphify", args: "." },
    ]);
  });

  it("3) caveat + 正文:caveat 段折叠、正文单独成段", () => {
    const segs = parseUserMessage(CAVEAT_PLUS_TEXT);
    expect(segs).toHaveLength(2);
    expect(segs[0].kind).toBe("caveat");
    expect(segs[1]).toEqual({ kind: "text", text: "\n帮我把 /tmp/repo 这个目录索引一下" });
  });
});
