import { describe, expect, it } from "vitest";
import {
  stripControlTags,
  summarizeSessionForCosmos,
} from "../src/workCosmos/summarize.js";
import type { Message } from "../src/cursorHistory/types.js";

function userMsg(content: string): Message {
  return {
    id: "u",
    role: "user",
    content,
    timestamp: new Date(),
    codeBlocks: [],
  };
}

function assistantMsg(content: string): Message {
  return {
    id: "a",
    role: "assistant",
    content,
    timestamp: new Date(),
    codeBlocks: [],
  };
}

describe("stripControlTags", () => {
  it("removes <local-command-caveat> wrappers", () => {
    const input =
      "<local-command-caveat>Caveat: messages were generated by the user</local-command-caveat>\n\nWhat does this code do?";
    expect(stripControlTags(input)).toBe("What does this code do?");
  });

  it("removes <command-message> / <command-name> / <command-args>", () => {
    const input =
      "<command-message>init</command-message>\n<command-name>/init</command-name>\n<command-args>--quick</command-args>\nactual user question here";
    expect(stripControlTags(input)).toBe("actual user question here");
  });

  it("removes <bash-input>/<bash-stdout>/<bash-stderr>", () => {
    const input =
      "<bash-input>git status</bash-input><bash-stdout>nothing to commit</bash-stdout>\n好了 接下来做什么";
    expect(stripControlTags(input)).toBe("好了 接下来做什么");
  });

  it("removes <system-reminder> blocks", () => {
    const input =
      "<system-reminder>The task tools haven't been used recently.</system-reminder>continue with cosmos";
    expect(stripControlTags(input)).toBe("continue with cosmos");
  });

  it("preserves substantive content when no tags present", () => {
    const input = "How do prompt-cache fields work in Claude tokens?";
    expect(stripControlTags(input)).toBe(input);
  });

  it("removes <local-command-stdout> / <local-command-stderr> wrappers", () => {
    const input =
      "<local-command-stdout>Set model to Opus</local-command-stdout>\n\nreal question";
    expect(stripControlTags(input)).toBe("real question");
  });

  it("strips ANSI escape sequences (SGR / CSI)", () => {
    // \x1B[1m bold ON, \x1B[22m bold OFF, \x1B[K clear-line
    const input = "\x1B[1mOpus\x1B[22m mode \x1B[Kactive — pose your question";
    expect(stripControlTags(input)).toBe("Opus mode active — pose your question");
  });
});

describe("summarizeSessionForCosmos", () => {
  it("returns null for empty / all-boilerplate sessions", () => {
    const messages = [userMsg("<command-message>init</command-message>")];
    expect(summarizeSessionForCosmos(messages)).toBeNull();
  });

  it("picks first substantive user + last substantive assistant", () => {
    const messages = [
      userMsg("<command-message>git status</command-message>"),
      assistantMsg("on branch main, working tree clean"),
      userMsg("Now let's design the cosmos schema for AI conversation embeddings"),
      assistantMsg("First boilerplate-only assistant reply"),
      userMsg("Some follow-up question"),
      assistantMsg(
        "Here's the schema: work_cosmos_points with session_id PK, work_cosmos_embeddings as sidecar..."
      ),
    ];
    const summary = summarizeSessionForCosmos(messages)!;
    expect(summary).toContain("Now let's design the cosmos schema");
    expect(summary).toContain("Here's the schema");
    // boilerplate first user should not appear
    expect(summary).not.toContain("<command-message>");
  });

  it("caps output at 2048 chars", () => {
    const long = "x".repeat(5000);
    const summary = summarizeSessionForCosmos([
      userMsg(long),
      assistantMsg(long),
    ])!;
    expect(summary.length).toBeLessThanOrEqual(2048);
  });

  it("falls back to first non-substantive user when nothing else", () => {
    const messages = [
      userMsg("hi"), // short but real
      assistantMsg("hello there, friend"),
    ];
    const summary = summarizeSessionForCosmos(messages)!;
    // assistant ≥20 chars → counts as substantive
    expect(summary).toContain("hello there, friend");
  });
});
