/**
 * 把 Claude Code transcript 里 `role:"user"` 记录的正文清洗成「用户真正手打的文本」。
 *
 * `src/claudeCodeHistory/normalize.ts` 的 `userVisibleFromContent` 把所有
 * `type:"text"` 块零过滤地拼接,所以 user 轮里除了你手打的,还混着机器注入:
 * 斜杠命令元数据、本地命令输出、`<system-reminder>`、Caveat 声明、中断提示。
 * 这些 `trim()` 后仍非空,不剥就会被当成「我说的消息」渲染、并让计数虚高。
 *
 * best-effort:只剥已知包装标记;未知的新标记可能漏。剥完为空 → 返回 ""，
 * 调用方据此丢弃该轮、也不计入条数。
 */

// 成对、可跨行的注入标记。
const PAIRED_TAGS = [
  "command-name",
  "command-message",
  "command-args",
  "command-contents",
  "local-command-stdout",
  "local-command-stderr",
  "system-reminder",
];

export function cleanUserMessage(raw: string): string {
  if (!raw) return "";

  // 0) 斜杠命令 / 技能调用:整轮都是机器展开(命令体 / skill 正文),用户其实只敲了
  //    `/xxx` 或触发了技能。整轮丢弃,而不是只剥标签留下命令体。
  //    - 含 `<command-name>`:斜杠命令元数据轮。
  //    - 以 `Base directory for this skill:` 开头:Claude Code 注入任何 skill 正文时
  //      的标准前缀(命令标签往往在另一个独立小轮里,这条正文轮本身是裸的)。
  if (/<command-name>/.test(raw)) return "";
  if (raw.trimStart().startsWith("Base directory for this skill:")) return "";

  let s = raw;

  // 1) 成对标记整块(含内容,可跨行)。
  for (const tag of PAIRED_TAGS) {
    s = s.replace(new RegExp(`<${tag}>[\\s\\S]*?</${tag}>`, "g"), "");
  }

  // 2) 残留的未闭合 / 自闭合同类标记。
  s = s.replace(
    /<\/?(?:command-[a-z-]+|local-command-[a-z]+|system-reminder)[^>]*>/g,
    ""
  );

  // 3) Caveat 声明整行(Claude Code 在本地命令上下文前注入)。
  s = s.replace(
    /Caveat: The messages below were generated by the user while running local commands\.[^\n]*/g,
    ""
  );

  // 4) 中断提示行(`[Request interrupted by user]` / `... for tool use]`)。
  s = s.replace(/\[Request interrupted by user[^\]]*\]/g, "");

  return s.trim();
}
